services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Live-reloads your code as you type
    depends_on:
      - db
      - minio # Tells Streamlit to wait for the Data Lake to boot up
    env_file:
      - .env  # Gives Streamlit/Python access to the DB & MinIO credentials

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5442:5432"  # Custom port 5442 to avoid your WSL/Windows conflicts
    volumes:
      - omnipulse_db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # The API Port (What your Python script talks to)
      - "9001:9001" # The Web Console Port (Where you log in to look at the files)
    volumes:
      - minio_data:/data

volumes:
  omnipulse_db_data:
  minio_data: # Creates a permanent hard drive for your CSV files