services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./omnipulse_dbt/profiles.yml:/root/.dbt/profiles.yml
    depends_on:
      - db
      - minio
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
      - STREAMLIT_SERVER_RUN_ON_SAVE=true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5442:5432"
    volumes:
      - omnipulse_db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  omnipulse_db_data:
  minio_data:
